# Generated by Django 3.0.3 on 2020-02-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='price',
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('SOUPS', 'SOUPS'), ('WRAPS', 'WRAPS'), ('BURITTOS', 'BURITTOS'), ('PANINIS', 'PANINIS'), ('BREAKFAST SANDWHICHES', 'BREAKFAST SANDWHICHES'), ('HOT DRINKS', 'HOT DRINKS'), ('GRILLED CHEESES', 'GRILLED CHEESES')], default='SOUPS', max_length=150),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.CharField(max_length=120),
        ),
    ]
